import ApolloProviderComponent from "./_components/ApolloProviderComponent";
import "./styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApolloProviderComponent>{children}</ApolloProviderComponent>
      </body>
    </html>
  );
}
